package tui

// DOOM and Quake are registered trademarks of id Software, Inc. The DOOM, Quake and id logos are trademarks of id Software, Inc.
// The ASCII version of the DOOM logo is Copyright © 1994 by F.P. de Vries.

// this logo is work from Frans P. de Vries who originally made it and nicely granted me permission to use it here
// details can be found in this little piece of video game history:
// http://www.gamers.org/~fpv/doomlogo.html

const (
	doomLogo2      = "[red]=================     ===============     ===============   ========  ========\n\\\\ . . . . . . .\\\\   //. . . . . . .\\\\   //. . . . . . .\\\\  \\\\. . .\\\\// . . //\n||. . ._____. . .|| ||. . ._____. . .|| ||. . ._____. . .|| || . . .\\/ . . .||\n|| . .||   ||. . || || . .||   ||. . || || . .||   ||. . || ||. . . . . . . ||\n||. . ||   || . .|| ||. . ||   || . .|| ||. . ||   || . .|| || . | . . . . .||\n|| . .||   ||. _-|| ||-_ .||   ||. . || || . .||   ||. _-|| ||-_.|\\ . . . . ||\n||. . ||   ||-'  || ||  `-||   || . .|| ||. . ||   ||-'  || ||  `|\\_ . .|. .||\n|| . _||   ||    || ||    ||   ||_ . || || . _||   ||    || ||   |\\ `-_/| . ||\n||_-' ||  .|/    || ||    \\|.  || `-_|| ||_-' ||  .|/    || ||   | \\  / |-_.||\n||    ||_-'      || ||      `-_||    || ||    ||_-'      || ||   | \\  / |  `||\n||    `'         || ||         `'    || ||    `'         || ||   | \\  / |   ||\n||            .===' `===.         .==='.`===.         .===' /==. |  \\/  |   ||\n||         .=='   \\_|-_ `===. .==='   _|_   `===. .===' _-|/   `==  \\/  |   ||\n||      .=='    _-'    `-_  `='    _-'   `-_    `='  _-'   `-_  /|  \\/  |   ||\n||   .=='    _-'          `-__\\._-'         `-_./__-'         `' |. /|  |   ||\n||.=='    _-'                                                     `' |  /==.||\n=='    _-'                                                            \\/   `==\n\\   _-'                                                                `-_   /\n `''                                                                      ``'"
	doomLogoBackup = "[royalblue]=================     ===============     ===============   ========  ========\n[royalblue]\\\\ . . . . . . .\\\\   //. . . . . . .\\\\   //. . . . . . .\\\\  \\\\. . .\\\\// . . //\n[orange]||[royalblue]. . .[orange]_____[royalblue]. . .[orange]|| ||[royalblue]. . .[orange]_____[royalblue]. . .[orange]|| ||[royalblue]. . .[orange]_____[royalblue]. . .[orange]|| ||[royalblue] . . .[orange]\\/[royalblue] . . .[orange]||\n[orange]||[royalblue] . .[orange]||   ||[royalblue]. . [orange]|| ||[royalblue] . .[orange]||   ||[royalblue]. . [orange]|| ||[royalblue] . .[orange]||   ||[royalblue]. . [orange]|| ||[royalblue]. . . . . . . [orange]||\n[orange]||[royalblue]. . [orange]||   ||[royalblue] . .[orange]|| ||[royalblue]. . [orange]||   ||[royalblue] . .[orange]|| ||[royalblue]. . [orange]||   ||[royalblue] . .[orange]|| ||[royalblue] . [orange]|[royalblue] . . . . .[orange]||\n[orange]||[royalblue] . .[orange]||   ||[royalblue]. [orange]_-|| ||-_[royalblue] .[orange]||   ||[royalblue]. . [orange]|| ||[royalblue] . .[orange]||   ||[royalblue]. [orange]_-|| ||-_[royalblue].[orange]|\\[royalblue] . . . . [orange]||\n[orange]||[royalblue]. . [orange]||   ||-'  || ||  `-||   || [royalblue]. .[orange]|| ||[royalblue]. . [orange]||   ||-'  || ||  `|\\_[royalblue] . .[orange]|[royalblue]. .[orange]||\n[orange]||[royalblue] . [orange]_||   ||    || ||    ||   ||_[royalblue] . [orange]|| ||[royalblue] . [orange]_||   ||    || ||   |\\ `-_/|[royalblue] . [orange]||\n[orange]||_-' ||  .|/    || ||    \\|.  || `-_|| ||_-' ||  .|/    || ||   | \\  / |-_[royalblue].[orange]||\n[orange]||    ||_-'      || ||      `-_||    || ||    ||_-'      || ||   | \\  / |  `||\n[orange]||    `'         || ||         `'    || ||    `'         || ||   | \\  / |   ||\n[orange]||            .===' `===.         .==='.`===.         .===' /==. |  \\/  |   ||\n[orange]||         .=='   \\_|-_ `===. .==='   _|_   `===. .===' _-|/   `==  \\/  |   ||\n[orange]||      .=='    _-'    `-_  `='    _-'   `-_    `='  _-'   `-_  /|  \\/  |   ||\n[orange]||   .=='    _-'          `-__\\._-'         `-_./__-'         `' |. /|  |   ||\n[orange]||.=='    _-'                                                     `' |  /==.||\n[orange]=='    _-'                                                            \\/   `==\n[orange]\\   _-'                                                                `-_   /\n[orange] `''                                                                      ``'"
	doomLogo       = "[royalblue]=================     ===============     ===============   ========  ========\n[royalblue]\\\\ . . . . . . .\\\\   //. . . . . . .\\\\   //. . . . . . .\\\\  \\\\. . .\\\\// . . //\n[orange]||[royalblue]. . .[orange]_____[royalblue]. . .[orange]|| ||[royalblue]. . .[orange]_____[royalblue]. . .[orange]|| ||[royalblue]. . .[orange]_____[royalblue]. . .[orange]|| ||[royalblue] . . .[orange]\\/[royalblue] . . .[orange]||\n[orange]||[royalblue] . .[orange]||   ||[royalblue]. . [orange]|| ||[royalblue] . .[orange]||   ||[royalblue]. . [orange]|| ||[royalblue] . .[orange]||   ||[royalblue]. . [orange]|| ||[royalblue]. . . . . . . [orange]||\n[orange]||[royalblue]. . [orange]||   ||[royalblue] . .[orange]|| ||[royalblue]. . [orange]||   ||[royalblue] . .[orange]|| ||[royalblue]. . [orange]||   ||[royalblue] . .[orange]|| ||[royalblue] . [orange]|[royalblue] . . . . .[orange]||\n[orange]||[royalblue] . .[orange]||   ||[royalblue]. [orange]_-|| ||-_[royalblue] .[orange]||   ||[royalblue]. . [orange]|| ||[royalblue] . .[orange]||   ||[royalblue]. [orange]_-|| ||-_[royalblue].[orange]|\\[royalblue] . . . . [orange]||\n[orange]||[royalblue]. . [orange]||   ||-'  || ||  `-||   || [royalblue]. .[orange]|| ||[royalblue]. . [orange]||   ||-'  || ||  `|\\_[royalblue] . .[orange]|[royalblue]. .[orange]||\n[orange]||[royalblue] . [orange]_||   ||    || ||    ||   ||_[royalblue] . [orange]|| ||[royalblue] . [orange]_||   ||    || ||   |\\ `-_/|[royalblue] . [orange]||\n[orange]||_-' ||  .|/    || ||    \\|.  || `-_|| ||_-' ||  .|/    || ||   | \\  / |-_[royalblue].[orange]||\n[orange]||    ||_-'      || ||      `-_||    || ||    ||_-'      || ||   | \\  / |  `||\n[orange]||    `'         || ||         `'    || ||    `'         || ||   | \\  / |   ||\n[orange]||            .===' `===.         .==='.`===.         .===' /==. |  \\/  |   ||\n[orange]||         .=='   \\_|-_ `===. .==='   _|_   `===. .===' _-|/   `==  \\/  |   ||\n[orange]||      .=='    _-'    `-_  `='    _-'   `-_    `='  _-'   `-_  /|  \\/  |   ||\n[orange]||   .=='    _-'          `-__\\._-'         `-_./__-'         `' |. /|  |   ||\n[orange]||.=='    _-'                                                     `' |  /==.||\n[orange]=='    _-'                                                            \\/   `==\n[orange]\\   _-'                                                                `-_   /\n[orange] `''                     [orange]twad[white] - [orange]t[white]erminal [orange]wad[white] launcher[orange]                     ``'"
)
